### ISSUE TITLE
How send data ?

### ISSUE THREAD

**Issue by damienmillet** [originphp/socket#1]
Hi, i don't understand how to send data.
for example if i use ur object 
<img width="317" alt="Capture d’écran 2020-05-23 à 19 13 56" src="https://user-images.githubusercontent.com/12233383/82736373-96f3c700-9d29-11ea-87dd-c00e9aaddbcd.png">

it's obvious than i forgot something but i don't know what.
How to receive my data from the server ?

**Comment by CrabThug** [comment]
u forgot a ] at the end here : https://github.com/originphp/socket#stream-contexts

**Comment by jamielsharief** [comment]
I am not sure i understand your question, but to read `$socket->read()` , if you look at the tests file you can see many different examples of how to use it.

**Comment by jamielsharief** [comment]
I have updated the readme, and added the missing bracket.

**Comment by CrabThug** [comment]
but my code read nothing :/

**Comment by jamielsharief** [comment]
I think for what you are trying to do, you should look WebSockets. See https://phppot.com/php/simple-php-chat-using-websocket/ for examples.

**Comment by jamielsharief** [comment]
Here is an example of communicating with a web server.
```
  $socket = new Socket([
            'host' => 'google.com',
            'port' => 443,
            'protocol' => 'ssl',
            'timeout' => 5
        ]);
      
        if ($socket->connect()) {
            $socket->write("GET https://about.google/intl/en/ HTTP/1.1\r\nConnection: close\r\n\r\n");
            print_r($socket->read(2500));
        }
        
        $socket->disconnect();
```

**Comment by CrabThug** [comment]
but sometimes u need to send data, not to redirect.
maybe need I to learn more about socket

**Comment by jamielsharief** [comment]
You need to first understand what you are doing, so if you are communicating with SMTP server, you need to know how that is done.

see https://www.php.net/manual/en/context.http.php and `follow_location` to disable following redirect.

**Comment by jamielsharief** [comment]
To send data use write, e.g `$socket->write($data)`

**Comment by jamielsharief** [comment]
I was just playing around to communicate via `wss` protocol, and did this code. There are php websocket implementations that you can use that will be easier and do not require a deep understanding of websockets and how they communicate.

```
        $socket = new Socket([
            'host' => '192.168.1.150',
            'protocol' => 'ssl',
            'port' => 8443,
            'timeout' => 30,
            'persistent' => false,
            'context' => [
                'ssl' => [
                    'verify_peer' => false,
                    'allow_self_signed' => true,
                    'verify_peer_name' => false,
                    'local_cert' => ROOT . '/config/client.pem',
                ]
            ]
        ]);

        // path =  /1.0/operations/123345/websocket?secret=foo
        if ($socket->connect()) {
            $socket->write('GET ' . $path . " HTTP/1.1\r\nHost: 192.168.1.150:8443\r\nAccept: */*\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: ".mt_rand(0, 999)."\r\n\r\n");
           
            $headers = $socket->read();
            $output = $socket->read();
            
            $this->out($output);
        }
        $socket->disconnect();
```
